# Generated by Django 5.0.6 on 2024-06-03 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_name_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('student', 'Student'), ('client', 'Client')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
