# Generated by Django 5.0.6 on 2024-06-03 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_purchasedetail_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_images/'),
            preserve_default=False,
        ),
    ]
