# Generated by Django 5.0.6 on 2024-06-04 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ligal_document',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='ligal_document/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='parents_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='parents_phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
