# Generated by Django 5.0.6 on 2024-06-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_ligal_document_customer_parents_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ligal_document',
            field=models.FileField(upload_to='ligal_document/'),
        ),
    ]
