# Generated by Django 5.0.6 on 2024-06-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdetail',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='SalesDetail',
        ),
    ]
