# Generated by Django 5.0.6 on 2024-06-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vat_pan_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
