# Generated by Django 5.0.6 on 2024-06-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customer_vat_pan_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ligal_document',
            new_name='legal_document',
        ),
    ]
