# Generated by Django 5.0.6 on 2024-06-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_rename_ligal_document_customer_legal_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('student', 'Student'), ('client', 'Client')], max_length=100),
        ),
    ]
