# Generated by Django 5.0.6 on 2024-06-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_customer_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('student', 'Student'), ('client', 'Client')], max_length=10),
        ),
    ]
