# Generated by Django 5.0.6 on 2024-06-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_salesdetail_sales_remove_salesdetail_product_and_more'),
        ('customer', '0014_alter_customer_customer_type'),
    ]

    operations = [
    ]
