# Generated by Django 5.0.6 on 2024-06-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_customer_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='legal_document',
            field=models.FileField(blank=True, null=True, upload_to='legal_document/'),
        ),
    ]
