# Generated by Django 5.0.6 on 2024-06-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_merge_20240607_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='legal_document',
            field=models.FileField(blank=True, null=True, upload_to='legal_document/'),
        ),
    ]
