# Generated by Django 5.0.6 on 2024-06-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_customer_legal_document'),
        ('customer', '0016_alter_customer_legal_document'),
    ]

    operations = [
    ]
