# Generated by Django 5.0 on 2024-06-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_customer_legal_document'),
        ('customer', '0016_alter_customer_legal_document'),
    ]

    operations = [
    ]
