# Generated by Django 5.0.6 on 2024-06-09 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_merge_20240607_1728'),
        ('customer', '0017_merge_20240608_1610'),
    ]

    operations = [
    ]
