# Generated by Django 5.0.6 on 2024-05-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_recurring',
            new_name='is_subscription',
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_period',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=50, null=True),
        ),
    ]
