# Generated by Django 5.0.6 on 2024-06-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_is_recurring_product_is_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isrecurring',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
