# Generated by Django 5.0 on 2024-06-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_isrecurring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subscription_period',
            new_name='recurring_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_subscription',
        ),
    ]
