# Generated by Django 5.0.6 on 2024-08-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_inventory_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_stock_required',
            field=models.BooleanField(default=False),
        ),
    ]
