# Generated by Django 5.0.6 on 2024-08-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_is_stock_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_stock_required',
            field=models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
