# Generated by Django 5.0.6 on 2024-05-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_customer_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
