# Generated by Django 5.0 on 2024-06-08 11:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_discount_sales_sub_total_sales_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('esewa', 'Esewa'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.sales')),
            ],
        ),
    ]
