# Generated by Django 5.0 on 2024-06-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='draft', max_length=50),
        ),
    ]
